### ISSUE TITLE
Support memchr4, memchr5, etc.

### ISSUE THREAD

**Issue by lfairy** [BurntSushi/rust-memchr#11]
I'm writing a routine that escapes HTML special characters. To do that, I have to search for five different characters (`&`, `<`, `>`, `'`, `"`) simultaneously. I can do this using two calls to `memchr2` or `memchr3`, but that doesn't seem elegant. It would be nice if there was a function that could do this search in one go.

From the implementation side: the PCMPESTRI instruction in SSE4.2 supports searching for up to 16 different needles in parallel. It would be nice if we could expose this somehow.

**Comment by BurntSushi** [comment]
It only makes sense to expose these functions if there is a performance
benefit over the naive solution. Last time I checked, there wasn't.

Implementing these with SSE instructions would be nice, but I'm not
particularly motivated to deal with that until it can feasibly work on Rust
stable. In the interim, you might find the jetscii crate useful.

**Comment by BurntSushi** [comment]
To be clear, the native solution is to create a `[bool; 256]` and check each byte in the haystack against that set. Alternatively, hard code the check for each byte. (See the benchmarks in this crate.)

**Comment by BurntSushi** [comment]
I'm going to close this because it's somewhat open ended. In order for these functions to make sense, there needs to be an experimental process that justifies their use. That is, I am firmly opposed to "just adding them" to complete the sequential pattern established by `memchr`, `memchr2`, `memchr3`, ...

Using explicit vector instructions would be nice here, but it would probably be nice *everywhere*. It would be interesting to see if we could compete with the hand rolled Assembly versions in glibc.
