### ISSUE TITLE
The road to add simd support?

### ISSUE THREAD

**Issue by kamyuentse** [BurntSushi/rust-memchr#32]
Now simd landed on nightly, do we have any plan to add the simd support?

**Comment by BurntSushi** [comment]
The libc memchr is probably already vectorized.

It would be a nice experiment to see if we can match or beat memchr using vendor intrinsics. Note though that GNU libc's memchr is, I believe, handwritten ASM.

This isn't a priority for me personally.

**Comment by BurntSushi** [comment]
I don't think there is any need to track this. SIMD isn't really a fixed goal. If people want to try their hand at making the fallback implementations faster, then that sounds like a fine idea.

**Comment by Alexhuszagh** [comment]
@BurntSushi, I just measured rust-memchr's performance, and everything is great with vectorized instrinsics, however, the fallback path is frequently quite similar in performance to naive Rust code. Would you accept PRs with vectorized instructions on other hardware if using a nightly compiler (since only x86 vendor intrinsics are stable)?

https://gist.github.com/Alexhuszagh/f9929e7d8e0277aa1281f511a841a167

![memchr1](https://user-images.githubusercontent.com/9440903/62426125-7da06200-b6a6-11e9-91d5-5645c71109bf.png)
![memchr2](https://user-images.githubusercontent.com/9440903/62426126-7da06200-b6a6-11e9-9beb-6e09ead64f4d.png)
![memchr3](https://user-images.githubusercontent.com/9440903/62426127-7e38f880-b6a6-11e9-95dc-539f0b1b7b89.png)

**Comment by BurntSushi** [comment]
Those plots are pretty misleading IMO, since they are on a log scale. The fallback implementation does much better (usually at least 2x) with respect to throughput when compared when the naive version. They tend to have similar characteristics (with naive sometimes being better) when the frequency of match is high, but that's somewhat expected and there's not much that can be done about that AFAIK.

> Would you accept PRs with vectorized instructions on other hardware if using a nightly compiler (since only x86 vendor intrinsics are stable)?

No, sorry. It's too much of a maintenance hazard. I generally do not use any nightly features in crates, _especially_ core crates like this. The best path forward here is to prototype it in a separate crate or get the intrinsics you need stabilized. (It's also plausible that `packed_simd` could be used, which would give you more portability.)

**Comment by Alexhuszagh** [comment]
@BurntSushi I mean, the log scale is for visualizing, but the idea that they are misleading is wrong. Simply put, the naive is slower than the fallback on the latest stable (Rustc 1.32.0) on x86_64 for 5/12 for memchr3, and only excels for memchr1. It's also only ~2x faster for the never and rare benchmarks. Otherwise it's typically within +/-10% of the naive implementation for most benchmarks. It's not a criticism, your crate has excellent performance for specific use-cases, and the fallback is generally good, I'm just looking to improve performance for more cases.

I understand the issues with maintenance, I'd be fine with adding packed_simd, if that's ok? That way we could have a single non-fallback path for nightly for non-x86 hardware, which would presumably simplify the maintenance and portability issue.

**Comment by BurntSushi** [comment]
I'm going to have to pass, sorry. Nightly only code is a maintenance hazard, as I mentioned in my previous comment. I've been through this before with other crates, and I've almost always regretted adding nightly-only code. On top of that, `packed_simd` takes an extremely long time to compile, which will make CI take longer.

**Comment by Alexhuszagh** [comment]
No worries, let me know if you ever change your mind, since I've already got a working implementation. I understand the maintenance concerns.
