### ISSUE TITLE
Clarity with regard to `--no-default-features` leading to `fallback::memchr`

### ISSUE THREAD

**Issue by flagello** [BurntSushi/rust-memchr#48]
First and foremost, thank you for the crate Andrew.

I’ve been employing it for a while, and I’ve recently made one of the libraries I’m working on `no_std`. Coincidentally while doing so, I altered my benchmarking habits, and never got hold of the fact `--no-default-features` leads to `fallback::memchr` due to `std::is_x86_feature_detected`, and only discovered the change via `cargo asm`.

What do you think of extending the README‘s `no_std` section to mention the otherwise “silent” requirement? 

(I am now using `std_detect` with an extern `no_std` memchr. Considering you work on that too, I assume you’ll want it to be stable before adopting it.)

**Comment by BurntSushi** [comment]
I actually don't work on `std_detect` haha. My name is probably on it because I started `stdsimd` and it just got copy & pasted.

In any case, you bring up a good point. I do think the docs should be updated, but I think this is a bug as well. In particular, we should be able to fall back to the SSE2 implementation on x86_64, since that doesn't require runtime CPU feature detection.
