### ISSUE TITLE
Provide lines-iterator

### ISSUE THREAD

**Issue by lukaslueg** [BurntSushi/rust-memchr#53]
I guess this came up before because it's so obvious: Provide an iterator akin to `std::str::lines`, but using `memchr` to search for line endings. The impl in `core::memchr` came up in my benchmarks and it turns out the code below is 2x to 3x faster than what `std::str::lines()` does, both in synthetic and real-life code.

```rust
pub fn lines(inp: &[u8]) -> impl Iterator<Item = &[u8]> {
    let mut inp = inp;
    std::iter::from_fn(move || {
        if inp.is_empty() {
            return None;
        }
        let ending = memchr::memchr(b'\n', inp).unwrap_or(inp.len() - 1) + 1;
        let (mut line, rest) = inp.split_at(ending);
        inp = rest;
        if let Some(b'\n') = line.last() {
            line = &line[..line.len() - 1];
            if let Some(b'\r') = line.last() {
                line = &line[..line.len() - 1];
            }
        }
        Some(line)
    })
}

pub fn str_lines(inp: &str) -> impl Iterator<Item = &str> {
    lines(inp.as_bytes()).map(|sl| unsafe { std::str::from_utf8_unchecked(sl) })
}
```

Is the performance difference (on my machine!) reason enough to include it in `memchr` ? Feel free if so :-)

**Comment by BurntSushi** [comment]
I think line iteration is beyond the scope of this crate.

Perhaps the `memchr` implementation in `core` could be improved. It can't use AVX2, but it could use SSE2 on x86_64, which is not that much slower than AVX2 for this particular case.

Otherwise, feel free to use [`bstr`](https://docs.rs/bstr), which has line iterators built on top of `memchr` in this crate.
