### ISSUE TITLE
Failure to build on Apple Silicon M1

### ISSUE THREAD

**Issue by Xe** [BurntSushi/rust-memchr#78]
Using [my site](https://github.com/Xe/site) code I attempted to build memchr using `cargo build`. The build.rs file fails to run with the following error:

```console
$ cargo build
   Compiling proc-macro2 v1.0.24
   Compiling libc v0.2.73
   Compiling syn v1.0.48
   Compiling memchr v2.3.3
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling ryu v1.0.5
   Compiling serde_derive v1.0.117
error: failed to run custom build command for `memchr v2.3.3`

Caused by:
  process didn't exit successfully: `/Users/cadey/Code/site/target/debug/build/memchr-08053740b12295b3/build-script-build` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I assume this may be a `rustc` bug as the error in question is identical to the error you get when you attempt to run an unsigned binary on an M1 Mac. I attempted to sign the binary manually with the `codesign` tool and it failed with this error:

```console
$ codesign -s - /Users/cadey/Code/site/target/debug/build/memchr-08053740b12295b3/build-script-build
/Users/cadey/Code/site/target/debug/build/memchr-08053740b12295b3/build-script-build: replacing existing signature
/Users/cadey/Code/site/target/debug/build/memchr-08053740b12295b3/build-script-build: the codesign_allocate helper tool cannot be found or used
```

Should I file this as a rustc bug?

**Comment by BurntSushi** [comment]
Yes. I don't see anything here for me to fix unfortunately.

**Comment by Xe** [comment]
I'll raise it in the Zulip. Thanks!

**Comment by shepmaster** [comment]
[discussion](https://rust-lang.zulipchat.com/#narrow/stream/242906-t-compiler.2Farm/topic/macOS.20build.20scripts.20and.20SIGKILL)

For future reference, this is an Apple bug.

[Why does my native arm64 application built using an x86_64 build system fail to be code signed unless I remove the previous executable?](https://stackoverflow.com/q/64830671/155423)

The fix is to ensure you have a complete aarch64 toolchain when building on aarch64. In this case, the problem was that `rustup` was still x86_64. Reinstalling it fixed the problem.

**Comment by BurntSushi** [comment]
Great, thank you for following up!
