### ISSUE TITLE
could we have a UTF-8 memchr?

### ISSUE THREAD

**Issue by llogiq** [BurntSushi/rust-memchr#8]
This could branch out to {`memchr`, `memchr2`, `memchr3`} depending on the first 4 bits of the `needle: char` argument. Alas, we have no `memchr4` function.

**Comment by BurntSushi** [comment]
Hmm, I think there might be some confusion, probably because of the very small amount of documentation on `memchr2` and `memchr3`. Namely, `memchr2` and `memchr3` search for *alternations* of 2 bytes and 3 bytes, respectively. They don't search for contiguous 2 or 3 byte sequences.

`memchr4` doesn't exist because when I tried to write it, I didn't see any measurable performance difference on x86_64. If you look at the benchmarks, you can see the dropoff between `memchr`, `memchr2` and `memchr3`.

**Comment by llogiq** [comment]
Thanks for clearing that up. I should probably have looked into the tests. Thank you.
